### PR TITLE
PR for Feature/friendship v2

### PR DESCRIPTION
**Pull request by Lameck1**
This pull request submits the following added features:

* Implement mutual friendship
  - One can see mutual friends on the show user page

* Refactor **`#friend?`**
  - This method now uses the **`has_many friends`** relationship to check whether a user is a friend to another user

* Refactor #destroy
   -  #destroy can now delete two rows of friendships between two users

* Refactor #all_friends_id
   -  #all_friends_ids now uses user.friends association

* Refactor #update to create two rows in Friendships

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Great job! 👏 You have done well on this project.
Let's make a few changes, and we will be done.

### Highlights
- Your Ruby-on-Rails skills are great. Great job with the implementation of friendship v2 👏 
- Your ReadMe file and Git commits are on point 💯 
- The implementation works just as expected 👍 
- Great tests coverage, excellent use of shoulda-matchers and capybara 👍 

### To Improve
- [x] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
see the affected file below:
> `app/views/layouts/application.html.erb`

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

- [x] You did a great job with the `confirm friend or Accept friend` in the update method of your friendship controller, but it could be better if we relieve our controller and let the model do the heavy lifting of handling most business logic. Calling this method from the model, instead of implementing the whole logic in the controller.
```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [x] Same as above we could have 
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
Then instead of having this logic in our controller
```ruby
  def timeline_posts
    posts = Post.where('user_id IN (?)', current_user.all_friends_ids)
    @timeline_posts ||= posts.ordered_by_most_recent
  end
```
We have ----
```ruby
  def timeline_posts
    @timeline_posts ||= current_user.friends_and_own_posts.ordered_by_most_recent
 end
```

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by Lameck1** [comment]
@acushlakoncept, thanks for the review. I have an issue with **`no logic in views`** though. I have done my best to exclude logic out of views as far as the scope of the assignment is concerned. The excessive use of **`logic in views`** that remains comes from the original code base and out of assignment scope. Am I supposed to refactor the whole application?

**Comment by acushlakoncept** [comment]
I understand your point, but that was just a template for you to use. I have seen your codebase, they are great. For you, it's quite a simple task. Move this to a helper method, say `show_auth_links` or something. You should be fine.
```ruby
      <% if current_user %>
         <div class="menu-item">
            <%= link_to current_user.name, user_path(current_user) %>
        </div>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', user_session_path %>
      <% end %>
```

**Comment by Lameck1** [comment]
@acushlakoncept, thanks so much for the detailed review. All suggestions now implemented.

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @Lameck1**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
